### ISSUE TITLE
[Suggestion] Widget settings should be accessible when using enhanced mode and no accessibility

### ISSUE THREAD

**Issue by gsxdsm** [KieronQuinn/Smartspacer#314]
### Suggestion

When using enhanced mode and no accessibility service, widget settings should still be shown.

**Comment by KieronQuinn** [comment]
This turned out to actually be a bug with the Shizuku service, it was already doing this but relied on the service running at the time the widget was configured (which was rare since it was crashing). It's fixed in 1.10.

**Comment by gsxdsm** [comment]
I updated and re added the widget, same issue is still occurring sorry!

**Comment by KieronQuinn** [comment]
If it's still occurring then the Shizuku service is genuinely stopped, so you'll have to use the Accessibility option instead.

**Comment by gsxdsm** [comment]
Shizuku is started. I disable and renable enhanced mode and confirm that Smartspacer is using enhanced mode, but when I go to configure the widget it won't show the widget settings and says accessibility service required. Everything else is using enhanced mode properly though. I think it's something in the widget config screen. I can't use accessibility service because of work profile restrictions.

**Comment by KieronQuinn** [comment]
The check on the widget config screen checks whether the Shizuku based foreground app listener is working, if it isn't then the widget cannot work without accessibility. It's not working for you, so accessibility is the only option here.

**Comment by gsxdsm** [comment]
Thanks - this is interesting - Smartspacer is correctly requesting Shizuku permissions, but you're right I don't see the foreground service. Does the foreground service always run or what conditions control that? I will dig into the code a bit this weekend and see if I can track down what's going on.
