### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by becksy82** [KieronQuinn/Smartspacer#396]
### Description

Hello,

I noticed that the alarm komplikationen doesnt recognice the Timezone correctly.
I Set Up the komplication in UTC+1 and now i am in utc +7.
But the komplication stills Shows the alarm in UTC+1. Eversthing in my Phone is Set to UTC+7

**Comment by SilverGreen93** [comment]
I have the same issue. Alarm is set to 7 am GMT+3, but the complication shows 6 am.

**Comment by SilverGreen93** [comment]
> ### Description
> 
> Hello,

Please edit issue title to something more descriptive about the actual issue.

**Comment by KieronQuinn** [comment]
Fixed in 1.11

**Comment by SilverGreen93** [comment]
I just upgraded to 1.11, but the issue is still not fixed. Can you link to the commit which supposedly fixed this issue?

**Comment by KieronQuinn** [comment]
The update now calculates the timezone format when the Complication is updated, so it is showing what the system is reporting. Which alarm app and device are you using?

**Comment by SilverGreen93** [comment]
> Which alarm app and device are you using?

I have a Xiaomi 14T phone running HyperOS 3 over Android 16.

I am using the default clock/alarm app (com.android.deskclock). Phone timezone is set to GMT+2 and daylight saving time, so it is UTC+3.

**Comment by KieronQuinn** [comment]
So you're not seeing this after the timezone changes, you're just seeing this in general? That would point to the system reporting the time in the wrong zone.

**Comment by SilverGreen93** [comment]
Yes, I am getting this incorrect behaviour in my home timezone.

I just opened a terminal and tested the output of date command:
![IMG_20260609_152403.jpg](https://github.com/user-attachments/assets/2f37e94e-9b6e-40f2-b81e-79f7979dd677)
It seems that both the time and timezone are correctly reported.

I doesn't look to me to be a system issue.

**Comment by KieronQuinn** [comment]
Not the same thing. The next alarm date is reported by the system in the AlarmManager class.

**Comment by SilverGreen93** [comment]
> Not the same thing. The next alarm date is reported by the system in the AlarmManager class.

So can it be that the issue is the alarm is reported without accounting for daylight saving time?

**Comment by KieronQuinn** [comment]
The time is supposed to be reported by that class as UTC, it works for other devices but it would make sense that Xiaomi managed to break it so it is reporting it taking daylight savings into account yeah.
