### ISSUE TITLE
[Bug] As of 1.3, if your homescreen allows screen rotation and you rotate your screen on Extended Smartspacer the app will crash

### ISSUE THREAD

**Issue by CamperSamu** [KieronQuinn/Smartspacer#57]
### Description

Since the new 1.3 update rotating the screen on Expanded Smartspacer triggers a crash of the app.
Exiting ExtSmartspace opening the home page, rotating the device and then reopening the ExtSmartspace won't crash the app, behaving correctly.

Tested on DerpFest 13 with the default launcher (DerpLauncher, com.android.launcher3)

**Comment by KieronQuinn** [comment]
Do you have the blurred background enabled in Expanded Smartspace settings? If so, try disabling it.

**Comment by CamperSamu** [comment]
Yes I do, disabling it doesn't trigger the crash.

**Comment by KieronQuinn** [comment]
This is working as intended then, the blur doesn't work on all launchers due to system rendering limitations and is already labelled as such.

**Comment by CamperSamu** [comment]
Thanks for fixing this bug in the end!
With version 1.6 (410c6d8003276b1c186d4a81f5e18ae71f71dba3) the crash has been fixed.

**Comment by KieronQuinn** [comment]
Yes, it turned out if blur gets disabled at exactly the right point (that thankfully the overlay does expose), it can be worked around. Still not sure why the system doesn't support rotating blurs but whatever.
